# Generated by Django 4.0.3 on 2022-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioWebApp', '0002_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
