# Generated by Django 4.0.3 on 2022-05-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioWebApp', '0003_alter_contacto_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='correo',
            new_name='email',
        ),
    ]
