# Generated by Django 4.0.3 on 2022-10-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioWebApp', '0004_rename_correo_contacto_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name_plural': '2. Contacto'},
        ),
        migrations.AlterModelOptions(
            name='proyectos',
            options={'verbose_name_plural': '1. Proyectos'},
        ),
    ]
